import React from 'react';
import { Navbar } from '../components/Navbar';
import { Footer } from '../components/Footer';
import { CartDrawer } from '../components/CartDrawer';
import { motion } from 'motion/react';

export const Studio = () => {
  return (
    <main className="bg-brand-primary min-h-screen">
      <Navbar />
      <CartDrawer />
      <div className="noise" />

      {/* Hero */}
      <section className="pt-40 pb-24 px-6 md:px-12">
        <div className="max-w-[1600px] mx-auto text-center mb-32">
          <motion.div
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
          >
            <span className="text-brand-accent-glow text-[11px] uppercase tracking-[0.6em] font-black mb-8 block">Veloura Design Studio</span>
            <h1 className="text-7xl md:text-[12rem] font-display font-black uppercase tracking-tighter leading-[0.7] mb-12">
              BEYOND <br /> <span className="text-hollow italic">THE FABRIC</span>
            </h1>
          </motion.div>
        </div>

        {/* Philosophy Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 lg:gap-24 mb-48">
          <div className="lg:col-span-7 aspect-[4/5] bg-brand-matte rounded-[4rem] overflow-hidden relative group">
             <img 
               src="https://images.unsplash.com/photo-1551232864-3f0890e580d9?q=80&w=1200&auto=format&fit=crop" 
               className="w-full h-full object-cover transition-transform duration-1000 group-hover:scale-105"
               alt="Fabric detail"
               loading="lazy"
               referrerPolicy="no-referrer"
             />
             <div className="absolute inset-0 bg-black/10 transition-colors group-hover:bg-black/0" />
             {/* Logo branding overlay */}
             <div className="absolute top-8 left-8 opacity-40 group-hover:opacity-100 transition-opacity flex items-center gap-2">
                <div className="w-8 h-8 rounded-full border border-brand-accent-glow/40 flex items-center justify-center font-serif relative">
                   <span className="text-[10px] font-bold bg-gradient-to-br from-brand-accent-glow to-white bg-clip-text text-transparent">V</span>
                   <span className="text-[10px] font-bold bg-gradient-to-br from-brand-accent-glow to-white bg-clip-text text-transparent absolute translate-x-1 -translate-y-1">Z</span>
                </div>
                <span className="text-[10px] uppercase font-black tracking-widest text-white">Studio</span>
             </div>
          </div>
          <div className="lg:col-span-5 flex flex-col justify-center">
             <h2 className="text-4xl md:text-6xl font-display font-black uppercase italic mb-8 leading-tight">
                Luxury <span className="text-brand-accent-glow">Brutalism.</span>
             </h2>
             <p className="text-xl text-white/60 font-light leading-relaxed mb-12">
                The Veloura Studio was founded on the belief that streetwear is the highest form of self-expression in the digital age. We don't just design clothes; we design avatars for the real world.
             </p>
             <div className="space-y-8">
                {[
                  { title: "Digital Synthesis", text: "Patterns generated by AI, refined by hand." },
                  { title: "Eternal Silhouettes", text: "Focusing on volume and architectural shapes." },
                  { title: "Circular Ethics", text: "100% sustainable deadstock materials." }
                ].map((item, i) => (
                  <div key={i} className="flex gap-6 pb-8 border-b border-white/5">
                    <span className="text-brand-accent-glow font-black font-display text-2xl">0{i+1}</span>
                    <div>
                      <h4 className="text-xs uppercase font-black tracking-widest mb-1">{item.title}</h4>
                      <p className="text-xs text-white/30 font-medium">{item.text}</p>
                    </div>
                  </div>
                ))}
             </div>
          </div>
        </div>

        {/* Team / Mission Full Width */}
        <div className="relative h-[80vh] rounded-[4rem] overflow-hidden mb-48 group">
           <img 
             src="https://images.unsplash.com/photo-1441984904996-e0b6ba687e04?q=80&w=2000&auto=format&fit=crop" 
             className="w-full h-full object-cover transition-transform duration-[3s] group-hover:scale-110"
             alt="Studio lifestyle"
             loading="lazy"
             referrerPolicy="no-referrer"
           />
           <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center p-12 text-center">
              <h2 className="text-5xl md:text-8xl font-display font-black uppercase mb-8">Culture Over Consumption</h2>
              <p className="max-w-2xl text-white/80 font-light text-lg">
                We release collections in "Editions" rather than seasons. Each piece is a numbered artifact, 
                designed to live in the archive of the modern individual.
              </p>
           </div>
        </div>
      </section>

      <Footer />
    </main>
  );
};
